### PR TITLE
Update to Swal v11

### PR DESCRIPTION
**Pull request by pjebs**

### CODE REVIEW

**Comment by pjebs** [comment]
@ZIMkaRU Can you check if this new update works.
I designed it to be backward compatable so you should not have to change any of your code.

Once you give the all-clear, I will merge to master and tag.

**Comment by ZIMkaRU** [comment]
> @ZIMkaRU Can you check if this new branch works.
> I designed it to be backward compatable so you should not have to change any of your code.
> 
> Once you give the all-clear, I will merge to master and tag.

Hey, so It broke the app, but don't worry, I would hardcode the `0.1.13` version and then will migrate to the version with Swal v11

**Comment by pjebs** [comment]
How did it break the app. The intention was it would be backward compatible

**Comment by pjebs** [comment]
Can you share the code you are using to allow the electron-alert?

**Comment by pjebs** [comment]
Could this line be causing the problem?

this.excludedFromShownWindowsMenu

**Comment by ZIMkaRU** [comment]
cought this error:

```console
ReferenceError: arg is not defined
    at BrowserWindow.<anonymous> (/home/vladimir/Documents/test/BitfinexReport-3.4.0-x64-linux/resources/app/node_modules/electron-alert/dist/alert.js:530:31)
```

looks like the error got from this
https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L526
`arg` option is redundant in this case
the same here:
https://github.com/rocketlaunchr/electron-alert/blob/master/src/alert.js#L503

**Comment by pjebs** [comment]
fixed.

**Comment by ZIMkaRU** [comment]
thanks)

**Pull request merged**
